# Generated by Django 5.2.1 on 2026-07-22 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("member", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManualPayments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payable_type_id", models.IntegerField(blank=True, null=True)),
                (
                    "receipt_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "proof_file_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("verified_by", models.IntegerField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "manual_payments",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MemberSavingObligations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monthly_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("is_active", models.BooleanField(blank=True, null=True)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_until", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "member_saving_obligations",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MonthlySavingBills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bill_period_start", models.DateField()),
                ("bill_period_end", models.DateField()),
                ("amount_due", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "amount_paid",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        null=True,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "monthly_saving_bills",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SavingTransactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_code", models.CharField(max_length=50, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("transaction_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "saving_transactions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SavingTypes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "minimum_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("is_mandatory", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "saving_types",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SavingWallets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "saving_wallets",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VoluntarySavingsRequests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "requested_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("status_id", models.IntegerField(blank=True, null=True)),
                (
                    "reject_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("processed_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "voluntary_savings_requests",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Withdrawals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "payment_reference_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "proof_file_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("request_date", models.DateTimeField(blank=True, null=True)),
                ("approved_date", models.DateTimeField(blank=True, null=True)),
                ("paid_date", models.DateTimeField(blank=True, null=True)),
                (
                    "reject_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "withdrawals",
                "managed": False,
            },
        ),
    ]
