# Generated by Django 5.2.1 on 2026-07-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccountingPeriods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("month", models.IntegerField(blank=True, null=True)),
                ("is_closed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "accounting_periods",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MasterConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("component_name", models.CharField(max_length=255)),
                ("percentage", models.DecimalField(decimal_places=2, max_digits=10)),
                ("distributed_member", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "master_configurations",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ShuComponentAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("component_name", models.CharField(max_length=255)),
                ("percentage", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "allocated_amount",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ("period_month", models.IntegerField()),
                ("period_year", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "shu_component_allocations",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ShuMemberBases",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_saving_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "shu_jasa_modal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "shu_member_bases",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ShuMemberDistributions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_savings",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "total_shu",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "simp_wajib",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "simp_sukarela",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("period_year", models.IntegerField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("transfer_proof", models.TextField(blank=True, null=True)),
                ("transfer_proof_url", models.TextField(blank=True, null=True)),
                ("transfer_proof_name", models.TextField(blank=True, null=True)),
                ("tf_reference_id", models.TextField(blank=True, null=True)),
                ("distributed_status", models.BooleanField(default=False)),
                ("status_shu", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "shu_member_distributions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ShuMemberDistributionsMonthly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_savings",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "total_shu",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("distributed_status", models.BooleanField(default=False)),
                (
                    "simp_wajib",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "simp_sukarela",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("status_shu", models.BooleanField(default=False)),
                ("period_month", models.IntegerField(blank=True, null=True)),
                ("period_year", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "shu_member_distributions_monthly",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ShuResults",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_year", models.IntegerField()),
                ("period_month", models.IntegerField(blank=True, null=True)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "total_expense",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "net_profit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("distributed_status", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "shu_results",
                "managed": False,
            },
        ),
    ]
