# Generated by Django 5.2.1 on 2026-07-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "principal_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "interest_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("start_date", models.DateField()),
                ("due_date", models.DateField()),
                (
                    "remaining_balance",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "loans",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LoanApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_requested",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("duration_months", models.SmallIntegerField()),
                ("purpose", models.CharField(max_length=255)),
                (
                    "salary_statement_file",
                    models.FileField(
                        blank=True, null=True, upload_to="loan/slip_gaji/"
                    ),
                ),
                (
                    "reject_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "loan_applications",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LoanInstallment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("installment_number", models.SmallIntegerField()),
                ("due_date", models.DateField()),
                (
                    "amount_principal",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "amount_interest",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("amount_total", models.DecimalField(decimal_places=2, max_digits=15)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "loan_installments",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LoanPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=15)),
                ("payment_date", models.DateTimeField()),
                ("payment_reference_id", models.IntegerField()),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "loan_payments",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LoanType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "loan_types",
                "managed": False,
            },
        ),
    ]
