# Generated by Django 5.2.1 on 2026-07-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("code", models.CharField(db_column="otp_code", max_length=10)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "email_otps",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="IncomeExpenseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[("INCOME", "Income"), ("EXPENSE", "Outcome")],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "income_expense_categories",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nik_ktp", models.CharField(max_length=50)),
                (
                    "nik_employee",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("full_name", models.CharField(max_length=100)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "place_of_birth",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=10, null=True)),
                ("department_id", models.IntegerField(blank=True, null=True)),
                ("employee_status_id", models.IntegerField(blank=True, null=True)),
                ("member_status_id", models.IntegerField(blank=True, null=True)),
                ("join_date", models.DateField(blank=True, null=True)),
                (
                    "ktp_file_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("npwp_file", models.CharField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("npwp_number", models.CharField(blank=True, max_length=50, null=True)),
                ("contract_end", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "members",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MemberBankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_id", models.IntegerField(blank=True, null=True)),
                (
                    "account_holder_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "account_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "member_bank_accounts",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MemberSavingObligation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("saving_type_id", models.IntegerField()),
                (
                    "monthly_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("effective_until", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "db_table": "member_saving_obligations",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PaymentChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel_code", models.CharField(max_length=50)),
                ("channel_name", models.CharField(max_length=100)),
                ("fee_percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                ("fee_fixed", models.DecimalField(decimal_places=2, max_digits=15)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "payment_channels",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role_name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "roles",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SHUComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("component_name", models.CharField(max_length=100, unique=True)),
                ("percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                ("distributed_member", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "master_configurations",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StatusCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "status_categories",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=255)),
                ("is_active", models.BooleanField()),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "users",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Withdrawal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "proof_file_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("request_date", models.DateTimeField()),
                ("paid_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "withdrawals",
                "managed": False,
            },
        ),
    ]
